<?php
/**
 * Theme functions and definitions.
 *
 * For more information on hooks, actions, and filters,
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package CodeSnippets
 * @since 1.0.0
 */

define('CODESNIPPETS_VERSION', '1.0.0');
define('PRISM_VERSION', '1.29.0');

/**
 * Enqueues the theme's styles and scripts.
 *
 * Hooks into the 'wp_enqueue_scripts' action to add the theme's CSS and
 * JavaScript files, as well as external libraries like Prism.js for
 * syntax highlighting.
 *
 * @since 1.0.0
 *
 * @return void
 */
function codesnippets_enqueue_assets()
{
	// Use filemtime for dynamic versioning to bust cache during development.
	$style_version = filemtime(get_template_directory() . '/assets/css/app.css');
	$script_version = filemtime(get_template_directory() . '/assets/js/app.js');

	// Main theme stylesheet generated by Tailwind CSS.
	wp_enqueue_style(
		'codesnippets-app-styles', // Unique, prefixed handle.
		get_template_directory_uri() . '/assets/css/app.css',
		[],
		$style_version
	);

	// Prism.js stylesheet for syntax highlighting (Okaidia theme).
	wp_enqueue_style(
		'codesnippets-prism-styles', // Unique, prefixed handle.
		'https://cdnjs.cloudflare.com/ajax/libs/prism/' . PRISM_VERSION . '/themes/prism-okaidia.min.css',
		[],
		PRISM_VERSION
	);

	// Main theme JavaScript file.
	wp_enqueue_script(
		'codesnippets-app-js', // Unique, prefixed handle.
		get_template_directory_uri() . '/assets/js/app.js',
		[], // Dependencies can be added here.
		$script_version,
		true
	);

	// Prism.js core library.
	wp_enqueue_script(
		'codesnippets-prism-core-js', // Unique, prefixed handle.
		'https://cdnjs.cloudflare.com/ajax/libs/prism/' . PRISM_VERSION . '/components/prism-core.min.js',
		[],
		PRISM_VERSION,
		true
	);

	// Prism.js autoloader plugin to dynamically load languages.
	wp_enqueue_script(
		'codesnippets-prism-autoloader-js', // Unique, prefixed handle.
		'https://cdnjs.cloudflare.com/ajax/libs/prism/' . PRISM_VERSION . '/plugins/autoloader/prism-autoloader.min.js',
		['codesnippets-prism-core-js'], // Dependency on our prefixed handle.
		PRISM_VERSION,
		true
	);
}
add_action('wp_enqueue_scripts', 'codesnippets_enqueue_assets');

/**
 * Registers the custom 'language' taxonomy for posts.
 *
 * Hooks into the 'init' action to create a non-hierarchical taxonomy
 * for categorizing snippets by programming language.
 *
 * @since 1.0.0
 *
 * @return void
 */
function codesnippets_register_taxonomy()
{
	$labels = [
		'name'          => _x('Languages', 'Taxonomy General Name', 'codesnippets'),
		'singular_name' => _x('Language', 'Taxonomy Singular Name', 'codesnippets'),
	];

	$args = [
		'labels'            => $labels,
		'hierarchical'      => false,
		'public'            => true,
		'show_ui'           => true, // Explicitly show in the admin UI.
		'show_admin_column' => true, // Show in the posts list table.
		'query_var'         => true,
		'rewrite'           => ['slug' => 'language'],
		'show_in_rest'      => true, // Enable for the block editor.
	];

	register_taxonomy('language', ['post'], $args);
}
add_action('init', 'codesnippets_register_taxonomy', 0);

/**
 * Displays custom-styled pagination links for archive pages.
 *
 * This function generates and echoes a complete pagination navigation block
 * with 'Prev' and 'Next' links, and numbered page links, styled with the
 * theme's custom CSS classes. It does not display if there is only one page
 * of posts.
 *
 * @since 1.0.0
 *
 * @return void
 */
function codesnippets_custom_pagination() {
	global $wp_query;

	$total_pages = $wp_query->max_num_pages;

	// Do not display pagination if there is only one page.
	if ($total_pages <= 1) {
		return;
	}

	$current_page = max(1, get_query_var('paged'));

	echo '<nav class="flex items-center justify-center space-x-2 mt-16" aria-label="Pagination">';

	// 'Prev' link.
	if ($current_page > 1) {
		printf(
			'<a href="%s" class="border-2 border-black bg-white px-4 py-2 font-bold uppercase text-black hover:bg-yellow-300 dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600 dark:hover:bg-yellow-300 dark:hover:text-black">Prev</a>',
			esc_url(get_pagenum_link($current_page - 1))
		);
	} else {
		echo '<span class="cursor-not-allowed border-2 border-neutral-400 px-4 py-2 font-bold uppercase text-neutral-400 dark:border-gray-700 dark:text-gray-600">Prev</span>';
	}

	// Numbered page links.
	for ($i = 1; $i <= $total_pages; $i++) {
		$active_classes   = 'bg-black text-yellow-300 dark:bg-yellow-300 dark:text-black dark:border-yellow-300';
		$inactive_classes = 'bg-white text-black hover:bg-yellow-300 dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600 dark:hover:bg-yellow-300 dark:hover:text-black';

		$link_classes = ($i === $current_page) ? $active_classes : $inactive_classes;
		$aria_current = ($i === $current_page) ? 'page' : 'false';

		printf(
			'<a href="%s" class="border-2 border-black px-4 py-2 font-bold uppercase %s" aria-current="%s">%d</a>',
			esc_url(get_pagenum_link($i)),
			esc_attr($link_classes),
			esc_attr($aria_current),
			$i
		);
	}

	// 'Next' link.
	if ($current_page < $total_pages) {
		printf(
			'<a href="%s" class="border-2 border-black bg-white px-4 py-2 font-bold uppercase text-black hover:bg-yellow-300 dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600 dark:hover:bg-yellow-300 dark:hover:text-black">Next</a>',
			esc_url(get_pagenum_link($current_page + 1))
		);
	} else {
		echo '<span class="cursor-not-allowed border-2 border-neutral-400 px-4 py-2 font-bold uppercase text-neutral-400 dark:border-gray-700 dark:text-gray-600">Next</span>';
	}

	echo '</nav>';
}

/**
 * Modifies the main search query to only include the 'post' post type.
 *
 * Hooks into 'pre_get_posts' to ensure that front-end search results only
 * return posts, excluding pages or other custom post types.
 *
 * @since 1.0.0
 *
 * @param WP_Query $query The WP_Query instance (passed by reference).
 * @return void
 */
function codesnippets_modify_search_query($query)
{
	if (is_admin() || !$query->is_main_query() || !$query->is_search()) {
		return;
	}
	$query->set('post_type', ['post']);
}
add_filter('pre_get_posts', 'codesnippets_modify_search_query');

/**
 * Redirects default search URLs to a "pretty" permalink structure.
 *
 * This function checks for standard search URLs (e.g., /?s=keyword) and
 * redirects them to a cleaner structure (e.g., /search/keyword) for better
 * aesthetics and SEO. It only runs if permalinks are enabled.
 *
 * @since 1.0.0
 *
 * @return void
 */
function codesnippets_nice_search_redirect()
{
	global $wp_rewrite;
	if (!isset($wp_rewrite) || !is_object($wp_rewrite) || !$wp_rewrite->using_permalinks()) {
		return;
	}

	$search_base = $wp_rewrite->search_base;
	$search_query = get_query_var('s');

	if (is_search() && !is_admin() && strpos($_SERVER['REQUEST_URI'], "/{$search_base}/") === false && !empty($search_query)) {
		wp_safe_redirect(home_url("/{$search_base}/" . urlencode($search_query)));
		exit();
	}
}
add_action('template_redirect', 'codesnippets_nice_search_redirect');

/**
 * Renders the list of tags for a given post.
 *
 * Generates and echoes a styled list of tags associated with a post.
 * If no post ID is provided, it defaults to the current post in the loop.
 *
 * @since 1.0.0
 *
 * @param int|WP_Post|null $post Optional. Post ID or post object. Defaults to the current post.
 * @return void
 */
function codesnippets_tags($post = null)
{
	$post_tags = get_the_tags($post);

	if (empty($post_tags) || is_wp_error($post_tags)) {
		return;
	}

	$tag_links = [];
	foreach ($post_tags as $tag) {
		$tag_links[] = sprintf(
			'<a href="%s" class="border border-black px-2 py-1 text-sm font-bold uppercase hover:bg-yellow-300 dark:border-gray-600 dark:hover:text-black">%s</a>',
			esc_url(get_tag_link($tag)),
			esc_html($tag->name)
		);
	}

	printf(
		'<div class="flex flex-wrap items-center gap-2" aria-label="%1$s">
			<div class="border border-black px-2 py-1 text-sm font-bold uppercase dark:border-gray-600">
				<span class="text-neutral-700 dark:text-neutral-300">%2$s</span>
			</div>
			%3$s
		</div>',
		esc_attr__('Post Tags', 'codesnippets'),
		esc_html__('tags:', 'codesnippets'),
		implode('', $tag_links)
	);
}
